Repository Activiti/Activiti, pull requests merged in 2018-11, with the labels that each got.

#2084 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.7
  pom.xml
Labels: updatebot

#2083 update org.activiti.api:activiti-api-dependencies to 7.0.37
  pom.xml
Labels: updatebot

#2131 update org.activiti.api:activiti-api-dependencies to 7.0.38
  pom.xml
Labels: updatebot

#2132 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.8
  pom.xml
Labels: updatebot

#2136 update org.activiti.api:activiti-api-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#2162 Create .mergify.yml
  .mergify.yml
Labels: enhancement, in progress

#2176 update org.activiti.build:activiti-parent to 7.0.40
  pom.xml
Labels: in progress, updatebot

#2169 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.13
  pom.xml
Labels: in progress, updatebot

#2156 update org.activiti.api:activiti-api-dependencies to 7.0.46
  pom.xml
Labels: in progress, updatebot

#2179 update org.activiti.api:activiti-api-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#2180 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.15
  pom.xml
Labels: in progress, updatebot

#2178 fix: (updatebot) use single pull request into activiti-dependencies
  .updatebot.yml
Labels: in progress

#2186 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.17
  pom.xml
Labels: in progress, updatebot

#2174 Trigger process deployed events
  activiti-spring-boot-starter/pom.xml
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/ProcessDeployedEventProducerTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/DeployedProcessesListener.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessDeployedEventIT.java
Labels: in progress

#2183 update org.activiti.build:activiti-parent to 7.0.41
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APITaskConverterTest.java
  activiti-engine/pom.xml
  activiti-spring/pom.xml
  pom.xml
Labels: in progress, updatebot

#2189 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.18
  pom.xml
Labels: in progress, updatebot

#2190 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.19
  pom.xml
Labels: in progress, updatebot

#2192 Missing id for BPMN element fixed
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
Labels: in progress

#2194 Missing id for BPMNElement #2175
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
Labels: in progress

#2193 Update process instance properties via API #2147
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ProcessUpdatedEventImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToProcessUpdatedConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ProcessUpdatedListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
Labels: in progress

#2191 update org.activiti.core.common:activiti-core-common-dependencies to 7.0.21
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
  pom.xml
Labels: in progress, updatebot

#2187 Fix missing processInstanceId in SequenceFlowTaken and VariableCreated events
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
  activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/event/impl/ToVariableCreatedConverter.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeEvents.java
Labels: in progress

#2207 Rename TaskExecutor to match with applicationTaskExecutor
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java
Labels: in progress

#2199 feat: add activiti-core-dependencies-tests module
  .mergify.yml
  activiti-api-impl/pom.xml
  activiti-bpmn-converter/pom.xml
  activiti-bpmn-layout/pom.xml
  activiti-bpmn-model/pom.xml
  activiti-core-dependencies-tests/pom.xml
  activiti-core-dependencies/pom.xml
  activiti-engine/pom.xml
  activiti-image-generator/pom.xml
  activiti-json-converter/pom.xml
  activiti-process-validation/pom.xml
  activiti-spring-app-process/pom.xml
  activiti-spring-boot-starter/pom.xml
  activiti-spring/pom.xml
  pom.xml
Labels: enhancement, in progress

#2208 fix(versions): update Activiti/Activiti versions
  pom.xml
Labels: in progress, updatebot

#2210 Load ProcessEngineAutoConfiguration after TaskExecutionAutoConfiguration
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AbstractProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/main/resources/META-INF/spring.factories
Labels: in progress

#2209 Implementation of processInstance update, tests added
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTest.java
Labels: in progress

#2216 Automated tests for dependencies convergence in CI pipelines for Activiti Cloud
  .mergify.yml
  activiti-core-dependencies-tests/pom.xml
  activiti-core-dependencies/pom.xml
  pom.xml
Labels: enhancement, in progress

#2219 fix(versions): update Activiti/Activiti versions
  pom.xml
Labels: in progress, updatebot

#2220 fix(versions): update Activiti/Activiti versions
  pom.xml
Labels: in progress, updatebot
