Repository Activiti/Activiti, pull requests merged in 2018-12, with the labels that each got.

#2232 2128 Initial work around conformance tests
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ProcessCompletedImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ProcessStartedEventImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToSequenceFlowTakenConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ActivityCancelledListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ActivityCompletedListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/ActivityStartedListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/SequenceFlowTakenListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/conf/CommonRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/event/internal/VariableDeletedListenerDelegate.java
  activiti-core-dependencies/pom.xml
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/deployer/BpmnDeployer.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/pom.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/Application.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicGenericTaskTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicProcessInformationTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ConformanceBasicProcessRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/ProcessInstanceOperationsTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/java/org/activiti/spring/conformance/set0/Set0RuntimeTestConfiguration.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/resources/processes/Process Information.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/resources/processes/Process with Generic  BPMN Task.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set0/src/test/resources/processes/UserTask with no User or Group Assignment.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/pom.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/Application.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceBasicProcessRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskModifyVariableTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/Set1RuntimeTestConfiguration.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/resources/processes/ServiceTask with Implementation.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/resources/processes/ServiceTask with Implementation2.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/pom.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/Application.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/ConformanceBasicProcessRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/Set2RuntimeTestConfiguration.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskAssigneeDeleteRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskAssigneeRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateDeleteRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateGroupRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateUserRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskNoCandidateRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/resources/processes/UserTask with Assignee.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/resources/processes/UserTask with CandidateGroup.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/resources/processes/UserTask with CandidateUser.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/resources/processes/UserTask with no User or Group Assignment.bpmn20.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-util/pom.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-util/src/main/java/org/activiti/spring/conformance/util/RuntimeTestConfiguration.java
  activiti-spring-conformance-tests/activiti-spring-conformance-util/src/main/java/org/activiti/spring/conformance/util/security/SecurityUtil.java
  activiti-spring-conformance-tests/pom.xml
  pom.xml
Labels: in progress

#2241 initial refactoring for candidateUsers and Groups
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimReleaseTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeDeleteTaskTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeTaskAssigneeTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeUnAuthorizedTest.java
  pom.xml
Labels: in progress

#2239 fix: fire ProcessUpdatedEvent added
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
Labels: in progress, ready-for-review

#2251 Fix: dispatch task and process updated events from CommandContext
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/TaskUpdatedListenerDelegate.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeImplTest.java
  activiti-engine/src/main/java/org/activiti/engine/TaskService.java
  activiti-engine/src/main/java/org/activiti/engine/impl/TaskServiceImpl.java
  activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SaveTaskCmd.java
  activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SetProcessInstanceNameCmd.java
  activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/TaskEntityManagerImpl.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateGroupRuntimeTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set2/src/test/java/org/activiti/spring/conformance/set2/UserTaskCandidateUserRuntimeTest.java
Labels: do-not-merge, in progress

#2240 fix: (IntegrationContext) add process instance execution context attributes
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskModifyVariableTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/ConformanceServiceTaskTest.java
  activiti-spring-conformance-tests/activiti-spring-conformance-set1/src/test/java/org/activiti/spring/conformance/set1/Set1RuntimeTestConfiguration.java
Labels: enhancement, in progress, ready-for-review

#2288 Add IntegrationContextBuilder unit tests
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/IntegrationContextBuilderTest.java
Labels: enhancement

#2293 fix(versions): update Activiti/Activiti versions
  pom.xml
Labels: updatebot

#2289 Resolve Execution entity parentProcessInstanceId attribute via Mybatis query mapping
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/connector/IntegrationContextBuilder.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APIProcessInstanceConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/connector/IntegrationContextBuilderTest.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APIProcessInstanceConverterTest.java
  activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntity.java
  activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityImpl.java
  activiti-engine/src/main/java/org/activiti/engine/impl/persistence/entity/ExecutionEntityManagerImpl.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/Execution.java
  activiti-engine/src/main/resources/org/activiti/db/mapping/entity/Execution.xml
  activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ExecutionQueryTest.java
  activiti-engine/src/test/java/org/activiti/engine/test/api/runtime/ProcessInstanceQueryTest.java
Labels: enhancement, ready-for-review

#2296 fix(versions): update Activiti/Activiti versions
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskAdminRuntimeImpl.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
  pom.xml
Labels: updatebot

#2308 fix(versions): update Activiti/Activiti versions
  pom.xml
Labels: updatebot

#2282 ProcessRuntime autodeploy process behaviour too aggressive
  .mergify.yml
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiProperties.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring/pom.xml
  activiti-spring/src/main/java/org/activiti/spring/SpringProcessEngineConfiguration.java
  activiti-spring/src/main/java/org/activiti/spring/autodeployment/AbstractAutoDeploymentStrategy.java
  activiti-spring/src/main/java/org/activiti/spring/autodeployment/FailOnNoProcessAutoDeploymentStrategy.java
  activiti-spring/src/main/java/org/activiti/spring/autodeployment/NeverFailAutoDeploymentStrategy.java
  activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/FailOnNoProcessAutoDeploymentStrategyTest.java
  activiti-spring/src/test/java/org/activiti/spring/test/autodeployment/NeverFailAutoDeploymentStrategyTest.java
  activiti-spring/src/test/resources/org/activiti/spring/test/autodeployment/errorHandling/parsing-error.bpmn20.xml
  activiti-spring/src/test/resources/org/activiti/spring/test/autodeployment/errorHandling/spring-context.xml
  activiti-spring/src/test/resources/org/activiti/spring/test/autodeployment/errorHandling/valid.bpmn20.xml
  activiti-spring/src/test/resources/org/activiti/spring/test/autodeployment/errorHandling/validation-error.bpmn20.xml
Labels: ready-for-review

#2229 BroadcastSignal not work with Activiti Core API and Activiti Cloud Rest API
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/RuntimeSignalPayloadEventListener.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/signal/SignalPayloadEventListener.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/conf/activiti/runtime/api/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeTest.java
  activiti-spring-boot-starter/src/test/resources/processes/SignalEventTest.testSignalStartEvent.bpmn20.xml
Labels: in progress
