Repository Activiti/Activiti, pull requests merged in 2019-07, with the labels that each got.

#2811 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2816 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2821 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2827 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2826 fix: remove `@Deprecated` for async executor and job apis
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/AsyncExecutor.java
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/ExecuteAsyncRunnableFactory.java
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/JobManager.java
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/multitenant/TenantAwareAsyncExecutor.java
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/multitenant/TenantAwareAsyncExecutorFactory.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/AdvancedCycleBusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/AdvancedSchedulerResolver.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/AdvancedSchedulerResolverWithTimeZone.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/AdvancedSchedulerResolverWithoutTimeZone.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/BusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/BusinessCalendarImpl.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/BusinessCalendarManager.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/CycleBusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DefaultBusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DueDateBusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DurationBusinessCalendar.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/DurationHelper.java
  activiti-engine/src/main/java/org/activiti/engine/impl/calendar/MapBusinessCalendarManager.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/Clock.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/ClockReader.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/DataObject.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/DeadLetterJobQuery.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/Job.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/JobQuery.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/SuspendedJobQuery.java
  activiti-engine/src/main/java/org/activiti/engine/runtime/TimerJobQuery.java
  activiti-engine/src/main/java/org/activiti/engine/test/Deployment.java
Labels: api

#2838 feat: externalize AsyncExecutor configuration properties
  activiti-engine/src/main/java/org/activiti/engine/impl/asyncexecutor/DefaultAsyncJobExecutor.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/AsyncExecutorProperties.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/AsyncExecutorConfigurationTest.java
  activiti-spring-boot-starter/src/test/resources/application-async-executor.properties
Labels: enhancement
