Repository Activiti/Activiti, pull requests merged in 2019-10, with the labels that each got.

#2904 fix: replaced component scans with auto configurations
  activiti-api-impl/activiti-api-process-runtime-impl/pom.xml
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ConnectorsAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-task-runtime-impl/pom.xml
  activiti-engine/src/test/resources/activiti.cfg.xml
  activiti-image-generator/pom.xml
  activiti-image-generator/src/main/java/org/activiti/image/impl/DefaultProcessDiagramGenerator.java
  activiti-spring-boot-starter/pom.xml
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiMethodSecurityAutoConfiguration.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/EndpointAutoConfiguration.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/MethodSecurityConfig.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/main/resources/META-INF/spring.factories
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessDeployedEventIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNErrorReceivedIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNSignalReceivedIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNTimerIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeVariableMappingTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/security/util/SecurityUtil.java
  activiti-spring-conformance-tests/activiti-spring-conformance-util/pom.xml
  activiti-spring-conformance-tests/activiti-spring-conformance-util/src/main/java/org/activiti/spring/conformance/util/RuntimeTestConfiguration.java
  activiti-spring-conformance-tests/activiti-spring-conformance-util/src/main/java/org/activiti/spring/conformance/util/security/SecurityUtil.java
  activiti-spring-conformance-tests/activiti-spring-conformance-util/src/main/resources/META-INF/spring.factories
  activiti-spring-process-extensions/pom.xml
  activiti-spring-process-extensions/src/test/java/org/activiti/spring/process/ProcessExtensionServiceIT.java
  activiti-spring/src/test/java/org/activiti/spring/test/fieldinjection/TestExecutionListener.java
  pom.xml
Labels: bug

#2939 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2941 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2938 fix(config): added conditional on missing `@EnableGlobalMethodSecurity` bean
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ActivitiMethodSecurityAutoConfiguration.java
Labels: bug

#2950 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2945 fix(AAE-201): Refactored TaskRuntime implementation to use extended SecurityManager groups Apis
  .gitignore
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeHelper.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeHelperTest.java
  pom.xml
Labels: bug

#2947 Validation of process and task variables names
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessAdminRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessRuntimeImpl.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/ProcessVariablesPayloadValidator.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/impl/ProcessRuntimeImplTest.java
  activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/conf/CommonRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-runtime-shared-impl/src/main/java/org/activiti/runtime/api/impl/VariableNameValidator.java
  activiti-api-impl/activiti-api-task-runtime-impl/pom.xml
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/conf/TaskRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskAdminRuntimeImpl.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeHelper.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskRuntimeImpl.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/impl/TaskVariablesPayloadValidator.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/impl/TaskRuntimeHelperTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/HistoryConfigurationTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/RuntimeTestConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessExtensionsJsonVarsTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessExtensionsTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNSignalReceivedIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeCallActivityMappingIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeConnectorIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeIT.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeVariableMappingTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeStandaloneTaskTest.java
  activiti-spring-boot-starter/src/test/resources/connectors/process-image.json
  activiti-spring-boot-starter/src/test/resources/processes/call-activity-subprocess-variable-mapping-extensions.json
  activiti-spring-boot-starter/src/test/resources/processes/call-activity-variable-mapping-empty-mapping-extensions.json
  activiti-spring-boot-starter/src/test/resources/processes/call-activity-variable-mapping-empty-mapping-with-task-extensions.json
  activiti-spring-boot-starter/src/test/resources/processes/call-activity-variable-mapping-extensions.json
  activiti-spring-boot-starter/src/test/resources/processes/variable-mapping-extensions.json
  activiti-spring-conformance-tests/activiti-spring-conformance-signals/src/test/java/org/activiti/spring/conformance/signals/SignalThrowCatchTest.java
  activiti-spring-process-extensions/src/test/resources/processes/default-vars-extensions.json
  activiti-spring-process-extensions/src/test/resources/processes/initial-vars-extensions.json
  activiti-spring-process-extensions/src/test/resources/processes/variable-mapping-extensions.json
Labels: ready-for-review
