Repository Activiti/Activiti, pull requests merged in 2019-09, with the labels that each got.

#2887 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2897 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2901 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2902 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2899 fix: Support BPMN Message Events XML export/import for correlationKey and messageExpression attributes
  activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/BaseBpmnXMLConverter.java
  activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/MessageEventDefinitionConverterTest.java
  activiti-bpmn-converter/src/test/resources/MessageEventDefinitionConverterTest.bpmn
Labels: enhancement, ready-for-review

#2903 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2909 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2913 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2918 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2919 fix(signal): dispatch ACTIVITY_SIGNALED start event within execution context
  activiti-engine/src/main/java/org/activiti/engine/delegate/event/impl/ActivitiEventBuilder.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateThrowSignalEventActivityBehavior.java
  activiti-engine/src/main/java/org/activiti/engine/impl/cmd/SignalEventReceivedCmd.java
  activiti-engine/src/main/java/org/activiti/engine/impl/cmd/TriggerCmd.java
  activiti-engine/src/main/java/org/activiti/engine/impl/event/SignalEventHandler.java
  activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java
  activiti-spring-conformance-tests/activiti-spring-conformance-signals/src/test/java/org/activiti/spring/conformance/signals/SignalThrowCatchTest.java
  activiti-spring-process-extensions/src/main/java/org/activiti/spring/process/ProcessVariablesInitiator.java
Labels: bug

#2924 fix(ACTIVITI-3874): handle duplicate event subscriptions for boundary and intermediate message events
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/AbstractThrowMessageEventActivityBehavior.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/BoundaryMessageEventActivityBehavior.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/behavior/IntermediateCatchMessageEventActivityBehavior.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultMessageExecutionContext.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/MessageExecutionContext.java
  activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageThrowCatchEventTest.java
Labels: bug

#2923 fix(ACTIVITI-3864): handle catch message expression and variable mappings
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/impl/RuntimeReceiveMessagePayloadEventListener.java
  activiti-engine/src/main/java/org/activiti/engine/impl/bpmn/parser/factory/DefaultMessageExecutionContext.java
  activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageIntermediateEventTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNMessageIT.java
  activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testBoundaryMessageExpression.bpmn20.xml
  activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testCatchMessageExpression-extensions.json
  activiti-spring-boot-starter/src/test/resources/processes/ProcessRuntimeBPMNMessageIT.testCatchMessageExpression.bpmn20.xml
Labels: bug

#2925 fix(ACTIVITI-3875): added support for interrupting and non-interrupting start message event for event subprocess
  activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java
  activiti-bpmn-converter/src/test/java/org/activiti/editor/language/xml/StartEventNonInterruptingEventSubprocessConverterTest.java
  activiti-bpmn-converter/src/test/resources/StartEventNonInterruptingEventSubprocessConverterTest.bpmn
  activiti-engine/src/main/java/org/activiti/engine/impl/agenda/EndExecutionOperation.java
  activiti-engine/src/test/java/org/activiti/engine/test/bpmn/event/message/MessageEventSubprocessTest.java
Labels: bug

#2927 ACTIVITI-3917 remove activiti: qualifier to the isInterrupting attribute for startEvent element
  activiti-bpmn-converter/src/main/java/org/activiti/bpmn/converter/StartEventXMLConverter.java
Labels: ready-for-review
