Repository Activiti/Activiti, pull requests merged in 2019-11, with the labels that each got.

#2967 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2974 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2976 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2977 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2971 feat(AAE-102): Added START_MESSAGE_DEPLOYED event api implementation
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/conf/ProcessRuntimeAutoConfiguration.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/MessageSubscriptionConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/StartMessageSubscriptionConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/impl/ToMessageSubscriptionCancelledConverter.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/main/java/org/activiti/runtime/api/event/internal/MessageSubscriptionCancelledListenerDelegate.java
  activiti-api-impl/activiti-api-process-runtime-impl/src/test/java/org/activiti/runtime/api/event/impl/MessageSubscriptionConverterTest.java
  activiti-engine/src/main/java/org/activiti/engine/impl/util/ProcessInstanceHelper.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/StartMessageDeployedEventProducer.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/boot/ProcessEngineAutoConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/MessageTestConfiguration.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/process/ProcessRuntimeBPMNMessageIT.java
Labels: enhancement

#2982 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2986 fix(AAE-201): Fixed the problem when process deployed and start message events are dispatched twice
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/AbstractActivitiSmartLifeCycle.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/ProcessDeployedEventProducer.java
  activiti-spring-boot-starter/src/main/java/org/activiti/spring/StartMessageDeployedEventProducer.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/ProcessDeployedEventProducerTest.java
Labels: enhancement

#3010 fix(versions): update Activiti/Activiti versions into develop
  pom.xml
Labels: updatebot

#2797 AAE-771 Support taskDefinitionKey in the Task model
  activiti-api-impl/activiti-api-task-runtime-impl/src/main/java/org/activiti/runtime/api/model/impl/APITaskConverter.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/APITaskConverterTest.java
  activiti-api-impl/activiti-api-task-runtime-impl/src/test/java/org/activiti/runtime/api/model/impl/MockTaskBuilder.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimReleaseTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeClaimTaskFromProcessTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeFormKeyTest.java
  activiti-spring-boot-starter/src/test/java/org/activiti/spring/boot/tasks/TaskRuntimeMultiInstanceIT.java
Labels: ready-for-review
