Repository Activiti/Activiti, pull requests merged in 2024-01, with the labels that each got.

#4527 [AAE-19256] - pre-checks fails in Activiti PRs from fork
  .github/actions/check-ext-build/action.yml
Labels: CI

#4537 Update README.md
  README.md
Labels: CI

#4529 [AAE-19314] New CI workflows to allow external contributions
  .github/actions/echo-longest-run/action.yml
  .github/workflows/main_pull.yml
  .github/workflows/main_push.yml
Labels: bug

#4528 AAE-19581 Activiti to Spring Boot 3.2.1
  pom.xml
Labels: dependencies, preview
